# Generated by Django 3.1.1 on 2020-09-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('start_study_id', models.BigIntegerField(null=True, verbose_name='Start Study ID')),
                ('end_study_id', models.BigIntegerField(null=True, verbose_name='End Study ID')),
                ('status', models.CharField(max_length=30, null=True, verbose_name='Status')),
                ('detail', models.TextField(blank=True, default=None, null=True, verbose_name='Detail')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(null=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Value')),
                ('datetime_value', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Datetime Value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(null=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('start_study_id', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Start Study ID')),
                ('end_study_id', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Start Study ID')),
                ('start_after', models.DateTimeField(null=True, verbose_name='Start After')),
                ('interval_value', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Interval Value')),
                ('interval', models.CharField(max_length=100, verbose_name='Interval')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(null=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True, verbose_name='Status')),
                ('crawled', models.DateTimeField(null=True, verbose_name='Crawled')),
                ('study_created', models.DateTimeField(null=True, verbose_name='Study Created')),
                ('study_updated', models.DateTimeField(null=True, verbose_name='Study Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(null=True, verbose_name='Updated')),
            ],
        ),
    ]
